// V4 art pipeline. Usage: node scripts/build-art.mjs
// raw-media/generated/*.png (AI-generated abstract art, never presented as photographs) -> public/images/art/<key>-{800,1600}.{avif,webp}
// plus a 24 px blur placeholder, written to src/data/art.ts. Sources are 1672 px wide, so 1600 is the largest honest size (no upscaling).
import sharp from "sharp";
import { mkdir, writeFile } from "node:fs/promises";

const SRC = "raw-media/generated", OUT = "public/images/art";
const ART = {
  "hero-poster": ["Hero poster (LCP fallback).png", "Rising bars of dark glass and brass with orange rim light and coins in the air, over a dark reflective floor."],
  manifesto: ["Manifesto background.png", "Raking warm light across an open accounting ledger beside a brass fountain pen."],
  "paper-tile": ["Paper texture tile.png", "Warm cream paper texture."],
  "pitch-stage": ["Pitch-stage abstract.png", "An empty stage with a lone lectern under one orange spotlight, rows of empty seats in the dark."],
  "sponsors-band": ["Sponsors band.png", "Stacked black stone and brass blocks like a podium, lit by orange light."],
  vortex: ["Vortex texture.png", "A spiral of orange and teal light particles around a bright core."],
  workshop: ["Workshopideas.png", "A dark desk with an open blank notebook, sticky notes, a pen and a laptop, lit warm."],
};
await mkdir(OUT, { recursive: true });
const rows = {};
for (const [key, [file, alt]] of Object.entries(ART)) {
  const base = sharp(`${SRC}/${file}`);
  const { width, height } = await base.metadata();
  for (const w of [800, 1600]) {
    const img = sharp(`${SRC}/${file}`).resize({ width: Math.min(w, width) });
    await img.clone().avif({ quality: key === "paper-tile" ? 40 : 52, effort: 6 }).toFile(`${OUT}/${key}-${w}.avif`);
    await img.clone().webp({ quality: 76 }).toFile(`${OUT}/${key}-${w}.webp`);
  }
  const blur = (await sharp(`${SRC}/${file}`).resize(24).webp({ quality: 40 }).toBuffer()).toString("base64");
  rows[key] = { w: 1600, h: Math.round((1600 * height) / width), alt, blur: `data:image/webp;base64,${blur}` };
  console.log(key);
}
await writeFile("src/data/art.ts", `// GENERATED by scripts/build-art.mjs. AI-generated abstract art: decorative backgrounds only, never shown as a photograph of the club.
export type ArtKey = ${Object.keys(ART).map((k) => `"${k}"`).join(" | ")};
export type Art = { w: number; h: number; alt: string; blur: string };
export const art: Record<ArtKey, Art> = ${JSON.stringify(rows, null, 1)};
`);
