// Panels for the vortex-expand tunnel: generated art (never photographs of people) and the club's own face-free posters, 1024 px WebP.
import sharp from "sharp";
import fs from "node:fs";
const GEN = { "boardroom-table.png": "boardroom", "cover-talk.png": "talk", "cover-workshop.png": "workshop", "hero-coin-macro.png": "coin", "map-glow-texture.png": "map-glow", "network-city.png": "network",
  "rocket-launch-abstract.png": "rocket", "sapling-macro.png": "sapling", "startup-ecosystem.png": "ecosystem", "trophy-plinth.png": "trophy", "Workshopideas.png": "ideas", "Pitch-stage abstract.png": "stage" };
const items = Object.entries(GEN).map(([f, s]) => [`raw-media/generated/${f}`, s]);
items.push(["raw-media/posters/venture_vortex.jpeg", "poster-announcement"], ["raw-media/posters/venture_vortex4.jpeg", "poster-why"]);
const meta = [];
for (const [src, slug] of items) {
  const info = await sharp(src).resize({ width: 1024, withoutEnlargement: true }).webp({ quality: 70 }).toFile(`public/images/dive/${slug}.webp`);
  meta.push({ slug, w: info.width, h: info.height, kb: Math.round(info.size / 1024) });
}
console.log(meta.map((m) => `${m.slug} ${m.w}x${m.h} ${m.kb}KB`).join("\n"), "\ntotal KB", meta.reduce((a, m) => a + m.kb, 0));
fs.writeFileSync("src/data/dive.ts", `// Generated by scripts/build-dive.mjs. Panels of the vortex-expand tunnel: generated art (not photographs) and the club's posters.\nexport const dive = ${JSON.stringify(meta.map(({ slug, w, h }) => ({ slug, w, h, poster: slug.startsWith("poster-") })), null, 1)} as const;\n`);
