// Club posters (raw-media/posters, supplied by the owner) -> public/images/posters/<slug>-{640,1024}.{avif,webp} + src/data/poster-blur.ts.
// Sources are 1113 px wide, so there is no 1600 variant: upscaling would be dishonest. sharp drops EXIF/ICC by default.
import sharp from "sharp";
import fs from "node:fs";
const MAP = { "venture_vortex.jpeg": "vv-announcement", "venture_vortex2.jpeg": "vv-tracks", "venture_vortex3.jpeg": "vv-timeline", "venture_vortex4.jpeg": "vv-why" };
const out = "public/images/posters";
fs.mkdirSync(out, { recursive: true });
const blur = {};
for (const [file, slug] of Object.entries(MAP)) {
  const src = `raw-media/posters/${file}`;
  for (const w of [640, 1024]) {
    const img = sharp(src).resize({ width: w, withoutEnlargement: true });
    await img.clone().avif({ quality: 52, effort: 6 }).toFile(`${out}/${slug}-${w}.avif`);
    await img.clone().webp({ quality: 74 }).toFile(`${out}/${slug}-${w}.webp`);
  }
  const b = await sharp(src).resize(16).webp({ quality: 40 }).toBuffer();
  blur[slug] = `data:image/webp;base64,${b.toString("base64")}`;
}
fs.writeFileSync("src/data/poster-blur.ts", `// Generated by scripts/build-posters.mjs. Do not edit.\nexport const posterBlur: Record<string, string> = ${JSON.stringify(blur, null, 2)};\n`);
console.log(fs.readdirSync(out).map((f) => `${f} ${(fs.statSync(`${out}/${f}`).size / 1024).toFixed(0)}KB`).join("\n"));
