// GENERATED by scripts/build-art.mjs. AI-generated abstract art: decorative backgrounds only, never shown as a photograph of the club.
export type ArtKey = "hero-poster" | "manifesto" | "paper-tile" | "pitch-stage" | "sponsors-band" | "vortex" | "workshop";
export type Art = { w: number; h: number; alt: string; blur: string };
export const art: Record<ArtKey, Art> = {
 "hero-poster": {
  "w": 1600,
  "h": 900,
  "alt": "Rising bars of dark glass and brass with orange rim light and coins in the air, over a dark reflective floor.",
  "blur": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAABwBACdASoYAA4APu1iqU2ppaQiMAgBMB2JYgCdAdwA3ERl6hItvVq0L7FAYAD+7xEU8kOeHuHGFasGmowayh4q0RDyyqJnWomkcmDS1NAZSSXfjp/gELjOGCllZZvVIz2lRHMYyYK11GFNp6sMI0fU7CWgWa9+/VcJ3aPgBoMJ7xzBM/KqTVkTb2ENH1iJqaxiMxquZ41huZ13/weFWMxgJxmx49+haabwtz4AAAA="
 },
 "manifesto": {
  "w": 1600,
  "h": 900,
  "alt": "Raking warm light across an open accounting ledger beside a brass fountain pen.",
  "blur": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAADwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdMoR4OsBxf4EB2ozpnSWNShyiq4AA/u9idxROHJKzZO6KvwJDb4/9YZDSU2nYd+ObTICcKV2L3IX+q2Nfu3TnG480k1greeq5nx+caMHHnOKO3BWRbgd+OWqLKgOtQB/SU3DHS3UIevWl9ftY9HKCbpl5Uy4TMkEvShcUGdaAAAA="
 },
 "paper-tile": {
  "w": 1600,
  "h": 900,
  "alt": "Warm cream paper texture.",
  "blur": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADwAgCdASoYAA4APu1iqU2ppaOiMAgBMB2JZwCw7DBsAAD+74jE9NUfPmYAAA=="
 },
 "pitch-stage": {
  "w": 1600,
  "h": 900,
  "alt": "An empty stage with a lone lectern under one orange spotlight, rows of empty seats in the dark.",
  "blur": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAACwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JQvKoN4lpgEIlvU9aQAD+78n6j9Zbw8vrGeR+/e4dH3eEcE8gRho1M4G3K3lhwTl/sD52Q4QzZWe6SJ0YSlKuNL9oP48No0sGOIt5l8xP3M1ROAPFroI9CIDINtPjNxn8lxwIAAA="
 },
 "sponsors-band": {
  "w": 1600,
  "h": 900,
  "alt": "Stacked black stone and brass blocks like a podium, lit by orange light.",
  "blur": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAQBACdASoYAA4APu1iqU2ppaQiMAgBMB2JagC258ADA06jOst1NapnmAD+8qIT7V3p5vI1pDb4o1JFOTC0ZYfSnDj6wVMOe3ohMWDsdTZS8bwKdXT7WgZUaK3+F/xq+raggutJ+B2phdx4yVidWBCzEyoHfu+CPXT/j61hDJeuOC6KbvQdZxPDb1re2XhcT1yIgIYA"
 },
 "vortex": {
  "w": 1600,
  "h": 900,
  "alt": "A spiral of orange and teal light particles around a bright core.",
  "blur": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAADwBACdASoYAA0APu1iqU2ppaOiMAgBMB2JbACdMoMYLKBz1WmAAUd2gkwfmXMOpqAA/uxJzcoYdKVHGcFJ1VQh9nl9MDpvJPkO+Q2pgDBVJ0YJ1gzmwRxvcHeVhdV0rH+wVL0iuyzJqb5VsNNkbhnMzcPPcpHtri/cL0BorZPtKNMpqn8GYrMkfZ2jE3NTo89mx1Af8y5ydz832CGV3NHkzb8Yn8P6zEzhIopDoFOiKB0wAAA="
 },
 "workshop": {
  "w": 1600,
  "h": 900,
  "alt": "A dark desk with an open blank notebook, sticky notes, a pen and a laptop, lit warm.",
  "blur": "data:image/webp;base64,UklGRt4AAABXRUJQVlA4INIAAADwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdMoFWADlgE4hPjmPODOi90qGwOoAA/u9OFWprXi8kPFnOWKEoSRFSgHbApL/ihF6wEEr/rnjrRmmRsGXXVFMkSs5yrmSUwQxSv8Wgn/ERQVtmdRmAyi1wBLWkYCzYDud0toHlbgpQ05DzZawg8DrfUuUF4iLY1BjYwVwshoHwuD3G8pPWX/9efUf32PRqO3n4p+gd3pmHeuvzgLjqXqsDneGaTWBymXDHSoMT2Pf7xe4jOYUAAAA="
 }
};
