// Generated by scripts/build-dive.mjs. Panels of the vortex-expand tunnel: generated art (not photographs) and the club's posters.
export const dive = [
 {
  "slug": "boardroom",
  "w": 1024,
  "h": 576,
  "poster": false
 },
 {
  "slug": "talk",
  "w": 1024,
  "h": 683,
  "poster": false
 },
 {
  "slug": "workshop",
  "w": 1024,
  "h": 683,
  "poster": false
 },
 {
  "slug": "coin",
  "w": 1024,
  "h": 576,
  "poster": false
 },
 {
  "slug": "map-glow",
  "w": 1024,
  "h": 576,
  "poster": false
 },
 {
  "slug": "network",
  "w": 1024,
  "h": 439,
  "poster": false
 },
 {
  "slug": "rocket",
  "w": 1024,
  "h": 576,
  "poster": false
 },
 {
  "slug": "sapling",
  "w": 1024,
  "h": 1280,
  "poster": false
 },
 {
  "slug": "ecosystem",
  "w": 1024,
  "h": 576,
  "poster": false
 },
 {
  "slug": "trophy",
  "w": 1024,
  "h": 1280,
  "poster": false
 },
 {
  "slug": "ideas",
  "w": 1024,
  "h": 576,
  "poster": false
 },
 {
  "slug": "stage",
  "w": 1024,
  "h": 576,
  "poster": false
 },
 {
  "slug": "poster-announcement",
  "w": 1024,
  "h": 1452,
  "poster": true
 },
 {
  "slug": "poster-why",
  "w": 1024,
  "h": 1452,
  "poster": true
 }
] as const;
