// Generated by scripts/build-dive.mjs. Panels of the dive tunnel: generated art only (not photographs, no posters, nothing about one competition).
export const dive = [
 {
  "slug": "boardroom",
  "w": 768,
  "h": 432,
  "poster": false
 },
 {
  "slug": "talk",
  "w": 768,
  "h": 512,
  "poster": false
 },
 {
  "slug": "workshop",
  "w": 768,
  "h": 512,
  "poster": false
 },
 {
  "slug": "coin",
  "w": 768,
  "h": 432,
  "poster": false
 },
 {
  "slug": "map-glow",
  "w": 768,
  "h": 432,
  "poster": false
 },
 {
  "slug": "network",
  "w": 768,
  "h": 329,
  "poster": false
 },
 {
  "slug": "rocket",
  "w": 768,
  "h": 432,
  "poster": false
 },
 {
  "slug": "sapling",
  "w": 768,
  "h": 960,
  "poster": false
 },
 {
  "slug": "ecosystem",
  "w": 768,
  "h": 432,
  "poster": false
 },
 {
  "slug": "trophy",
  "w": 768,
  "h": 960,
  "poster": false
 },
 {
  "slug": "ideas",
  "w": 768,
  "h": 432,
  "poster": false
 },
 {
  "slug": "stage",
  "w": 768,
  "h": 432,
  "poster": false
 }
] as const;
