// GENERATED by scripts/build-events.mjs from raw-media (not committed). Edit alt/focal/ratio in the script and re-run.
export type EventPhoto = { n: number; w: number; h: number; ratio: "3:2" | "4:5"; focal: string; alt: string; blur: string };
export const eventPhotos: Record<"valuation-wars" | "pitcher-perfect" | "the-pitch-league", EventPhoto[]> = {
 "valuation-wars": [
  {
   "n": 1,
   "w": 1600,
   "h": 899,
   "ratio": "3:2",
   "focal": "50% 60%",
   "alt": "Students in a tiered lecture hall, many with an arm raised and a white paddle in hand, seats full behind them.",
   "blur": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAQBACdASoYAA0APu1kqU2ppaOiMAgBMB2JQBadAt1RwSGxnk0tHHR0AADVD5DnGM3N0shUK+T7SNOuvDQ+67kTtrHcrk40achcH4/IpTlnzgqWyQ6uNaQgflMDH2H2z2xbjbi0K4KdZwZNlxQIfbZx0rVYiWmD9nuMGu9034Le2Y799iaZAylpCAAAAA=="
  },
  {
   "n": 2,
   "w": 1200,
   "h": 1600,
   "ratio": "4:5",
   "focal": "50% 55%",
   "alt": "Close view of students in the hall with hands and white paddles raised, several looking toward the camera.",
   "blur": "data:image/webp;base64,UklGRg4BAABXRUJQVlA4IAIBAADwBQCdASoYACAAPu1qrFEppaQiqAqpMB2JQACiA927OFm5Gf/pu2ECSTyTGtm8Ni0uvegijT2N4AD88gwHgyc/xawkmvmv9KNjODvCBw8+RjR+wCpAPvHME9E7EUuTPRcp1xOuVjCTis4RvUaArkSOG08EC9WQYdaw37b6S5ADOkbuRId3CU+W+868xuJJkF2uXyL0nwgQPpesbRe/NTcQOtRgkYdRmgq6q94UlrAonqA7nsJDtDW7/i/elVC8pIaG/75OBJSJiHhx9AVoTukk7PVWOf2++E+eMS2+cj7M2lXjGJzZUM79IRHG7dM6gi6FcQu2ulkY2Xbg1Vjp5YDsUAA="
  },
  {
   "n": 3,
   "w": 1600,
   "h": 900,
   "ratio": "3:2",
   "focal": "50% 65%",
   "alt": "Wide view of a full lecture hall, students standing and seated, a few holding paddles up.",
   "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACwAwCdASoYAA0APu1iqU2ppaQiMAgBMB2JYwCsABSSnD4AqsVOAAD6TVkZq0j0B7h5+PyEohcWwJvoGCdv7WBLPfoNSR+3v3M1kjPG37+piyh/KzK/u/xmP5sSPTrS6wXz0R67xhJDQzPFoMA+FiKJ2jEys5i1LBngORx4riqgAA=="
  },
  {
   "n": 4,
   "w": 1600,
   "h": 900,
   "ratio": "3:2",
   "focal": "40% 65%",
   "alt": "Students crowd the aisle and front rows of the hall, some holding white paddles.",
   "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADQAwCdASoYAA0APu1iqU2ppaQiMAgBMB2JYwAAP/DRdJjpaNzV9/gA/cT0+NEuOf3DpECusS7u7CeKiWH5hvcXOIK1+UdEaUkqYaOGzVwm5MMau3VAy9LRvDTgqDmGLnsmUIOru1+jH9vOfUtiC77/vKGL2RWi2HTNlN+50Wq1jHcdmc2miEYGAAA="
  },
  {
   "n": 5,
   "w": 1600,
   "h": 1200,
   "ratio": "3:2",
   "focal": "50% 55%",
   "alt": "The hall seen from the back: a seated audience facing a projector screen, a presenter standing near the lectern.",
   "blur": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAABQBQCdASoYABIAPu1qrVCppaQiqAqpMB2JZQDGQBIluJ03l9JTS2hPxfeEGM+N3lpJ5CAA4l9VRBiVEcV/DZUX6OMMwlSn4b1LLvMO127MpNkZtYHf07VszZEwpL6NqUpuOjjLnXznKDaYucmixGJVTd4Kl90mDNYhOpfMDkAba0PydE+JW+6JYCiFBc22HQY6wLnTSbC4AQcsRRbarHV6K4wv/JDGZ7UwuaxCl+PK6FLx3+3eaPKtlKkPtQAA"
  },
  {
   "n": 6,
   "w": 1600,
   "h": 900,
   "ratio": "3:2",
   "focal": "80% 60%",
   "alt": "A student speaks into a microphone at the right of the hall while the audience watches.",
   "blur": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAwBACdASoYAA0APu1iqU2ppaQiMAgBMB2JYwC1CNiCUa3MpfGTctOMMyAA/KZN6ISAP6BPNb3owlluXEmn/em4uWT/rPzSP9h50CLfIX7hHjHRPpyVwOU2D7wDhr+Tfv3ryLxwUAO+i3yIGo2qdow0+WSnqAbwe+tPv/bi7EPymUZN3QZ6N0h5rrx2CloAAAA="
  }
 ],
 "pitcher-perfect": [
  {
   "n": 1,
   "w": 1200,
   "h": 1600,
   "ratio": "4:5",
   "focal": "55% 60%",
   "alt": "Two students seated at a wooden desk reading papers together, more students at desks behind them.",
   "blur": "data:image/webp;base64,UklGRgYBAABXRUJQVlA4IPoAAABQBQCdASoYACAAPu1irU2ppaSiKA1RMB2JZACdAdwLiL5NGmcy+u3xwCjvIaulrua7LMAA/t6EySgclSILNMo3wviSuollkzczhZpsKU0YXqwCWPcY8KW5YuaczPFIjUPKgEXqg+CMpYy/gm5+gzj6+aXMYwC6DNFkEmlhU4eGVnuf+b8LPwsbBPY0Dn+EWm73FO56dlTpHkIP+HBZDp5juO5X/rZN+Wj7n0lTIg+cP02cSMj24vUCT69J68HpDACn2iZvckuO00YLDlmPE/FyMrp5patdfzExwJcrMqcz1J+u7+yxoG/X1W5bt8yu6965peweNc4vKQAA"
  },
  {
   "n": 2,
   "w": 1600,
   "h": 1200,
   "ratio": "3:2",
   "focal": "45% 60%",
   "alt": "Students in rows of wooden desks in a classroom, one standing at the right.",
   "blur": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAABwBQCdASoYABIAPu1srFEppaQiqAqpMB2JZQDDfiAByxiDgOW2UmXd8hBCzGrSVlWY9DLgAP5R3gnCP8Y8pqnBcD/aL8DHnTCOCrMj8ZZC3SFofMeo0bprXfF7BVgpmqAwhGd/8GT9So9p3W7Zv70xdVBfKEn35sSoYh5ud/RIJiKgnHII2m9Irg+ywDi5DFuiWh34eWudEuTHVqq2vZroCsVSGF1XAAA="
  },
  {
   "n": 3,
   "w": 1600,
   "h": 697,
   "ratio": "3:2",
   "focal": "55% 50%",
   "alt": "A classroom with a projected slide on the front wall and students at desks facing it.",
   "blur": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABQBACdASoYAAoAPu1iqU2ppaQiMAgBMB2JYwC06CBr/q2b3+qWMNUtb+AAAP5gyehpRAXBt6UfnLJXZSvjPVJ1p+lqxQfRvsxMBcTjTn8leJ1hPh7Iye4SB/CVgR0IrzVjd9cvMJ9A9To3vSAazYW0oI00a+zjZZ8t9hkkeNNBK2NpuKgdHQ6kNWAAAA=="
  },
  {
   "n": 4,
   "w": 1600,
   "h": 1200,
   "ratio": "3:2",
   "focal": "40% 50%",
   "alt": "Students seated at desks in a daylit classroom, facing a projected slide at the front.",
   "blur": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAADwBACdASoYABIAPu1ur1IppiQiqAgBMB2JYwDImYz4Rd3kWaUWBxRxhwGn+da4/CAAzXK3kOEC2gYiiC2ltRMgWkLmLau/soUIhae2DW+u9eESqMO6oVnX6Iaip9mqo+cfWzcuTCB51Xj5AmzckLO2H1ie+4pxhiRCSVU3jcdMS/R0GLsHWLNGEAHjdrZfEpUzNkYk6dTqDvUi9Gl/Jo6ln4BVggBzAZ/b1B3caKWaxwB7XZk3kwA0PWpAAA=="
  },
  {
   "n": 5,
   "w": 1600,
   "h": 1200,
   "ratio": "3:2",
   "focal": "55% 60%",
   "alt": "Two students stand beside a lectern next to a projected slide while others sit at a desk on the left.",
   "blur": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAADwBACdASoYABIAPu1eqE6ppKOiMBgMATAdiUAToAIWxnNfYNKLPT4ISgjyc4WV7kAA/sO8x2OWGs6b5Bi2et7d7TlTTVDMj0KjHIbIIZ5xpWUCuVvQ8AJU0IW1K+2Gdvdprj5AMrGPmMNNg2nIrXXIgYUA6L2vdvb16pcN2pFNeXxTJcS8TPXiU95Lj1in7Q3uW2TCIdJ4Kctv+tAoRTAjkzXzqAAA"
  },
  {
   "n": 6,
   "w": 1600,
   "h": 1200,
   "ratio": "3:2",
   "focal": "60% 65%",
   "alt": "Students working in pairs and small groups at wooden desks in a classroom.",
   "blur": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAADwBACdASoYABIAPu1qr1CppaQiqAqpMB2JYwC/OYxsbcsdHwgcECOXft+eby3b/QAA/pAkbDtSFZH0wGCpnfYoXgvo2VZvyOgrSMwa22n47JRwnHMxXu5odr+0o4dwZ6ObPGCzD24xhaSYDP+twdE2qE5J/1+akyPvA9j8UhtEgteDYjy0rEWR6Abtvaq6eqj36RW/0bqgVeursb3GeO8YX8tm7vfDBdzy82ftRkou30sVbImLdKRmlQ0UAA=="
  }
 ],
 "the-pitch-league": [
  {
   "n": 1,
   "w": 1600,
   "h": 720,
   "ratio": "3:2",
   "focal": "22% 50%",
   "alt": "Two students shown in profile, one gesturing toward something out of frame, in front of a whiteboard and a window.",
   "blur": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAAAQBACdASoYAAsAPu1iqU2ppaOiMAgBMB2JYgCsABZzZ/lc/Rq426vTAAD+6evS8yAEu5MQUPtH1hUMe8uVO7uqPxlbGOiRgcsCwewV1Xe8jRzV3QIoWg6YLK6ONiTcY5t/jNpKMP7zdK3MshG5R2jWtEoVl/KPZzl3upiTvbO+ZcI6TQD8dFY0Wek1O4Co/JGHxWcZD8fGmRHEK1ssdnfAAAA="
  },
  {
   "n": 2,
   "w": 1600,
   "h": 720,
   "ratio": "3:2",
   "focal": "45% 50%",
   "alt": "Two presenters stand beside a projector screen in a classroom while seated students watch.",
   "blur": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAACwBACdASoYAAsAPu1iqU2ppaOiMAgBMB2JagC7IKtJ/i15j23IbmXlbj3OM3YAAM1o+49FJxGf5BJf40QNktRnO6a2QKNdE3rd8BQnz0xowjO4SLgayMGWVNM29FGYoyU0RL56SZ3yQ1f37eTOAnvCwe8VdUxVty9PzlHGMYF/wcGjHkVXjvn4khwH1pj7nj7bydsX/yS4D13ipMDbW6GfolWdvLmQzlENekyuEg3zJdAA"
  },
  {
   "n": 3,
   "w": 1600,
   "h": 720,
   "ratio": "3:2",
   "focal": "38% 50%",
   "alt": "A student presents in front of a projected screen while seated classmates look on.",
   "blur": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAADwAwCdASoYAAsAPu1iqU2ppaOiMAgBMB2JQBOgMXXPa4NOhY4RxgpgAP5kdqIgzevfRuSyQE0p076qvA7t6RdSF659YUIGQaKd8azplSwKiwSnjRNGUX7qpZDZdtO5pUaPuV+JZ0BRQl5HENfjU83nJf6S3e9THl2FKJflfoSwV8PJA+EGqR0Ej/5waiMSDyV8EzFMoN5Jq/dGuAA="
  },
  {
   "n": 4,
   "w": 1600,
   "h": 720,
   "ratio": "3:2",
   "focal": "22% 50%",
   "alt": "A student in a brown sweater gestures as he presents to students seated by the windows.",
   "blur": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABwBACdASoYAAsAPu1iqU2ppaQiMAgBMB2JYwCdMoADC596uDaPbguFkfj4AADxDsSRic+ZXpF10cd3i2BoFdFrLlj3X3jO/mRgy9GndtHa+aevPIf7lziabcqKJBscPDwsyVonAyCq9F5n4/JJDnRuMMPobr5Z8LQ4gJVqGIXYaHmtYi6qkwAA"
  },
  {
   "n": 5,
   "w": 1600,
   "h": 720,
   "ratio": "3:2",
   "focal": "40% 50%",
   "alt": "A student speaks in front of a chalkboard that reads The Pitch League, a projected slide beside it.",
   "blur": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAABwBACdASoYAAsAPu1iqk2ppaQiMAgBMB2JZACdIIlmAKDwTXClm1hA/N+QYADOJ2qzXE9tfl1d03zNd0KPnTNFdVhrgtWwZ8o6IszwBBzI+L1cKRRqygMI6IbW840Wsgn1Dpb0n8iW7PbX/XY++vEZi9Sxf67CGmTw97hqMm73KkuO/Mlv4N5A9rg16fg+p2V4L+vO8gXe0We00eQkMU7+Bs4AAA=="
  },
  {
   "n": 6,
   "w": 1600,
   "h": 720,
   "ratio": "3:2",
   "focal": "38% 50%",
   "alt": "A student stands at the lectern, back partly to the camera, facing students seated along the windows.",
   "blur": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAAAQBACdASoYAAsAPu1iqU2ppaOiMAgBMB2JYwDCgCbfvmqS+G4p6yoMAAD4YlcP6dXFoVnW1R8fPEgno8DQi2uhwq/TwCi2KRoGvyX9TuO+wxf87UCySPg/bKFSPBRlc3ZzoNwZB/nfzi27ecPz0ihZ81FxuWpJ9fcuV7CSg8GdBVdxvAHKn3knhZjFrSVeFV+4nitFCT2J4AAA"
  }
 ]
};
