// GENERATED by scripts/build-media.mjs from raw-media (not committed). Edit alt/caption by re-running the script.
// Consent: owner statement 30 Sep 2026 that the club confirmed consent for people shown in these photos.
export type MediaRole = "hero" | "dive" | "moments" | "gallery";
export type Photo = {
  id: string; event: string;            // event = slug of an entry in data/events.ts
  w: number; h: number;                  // pixel size of the 1600 variant
  alt: string; roles: MediaRole[];
  blur: string;                          // 24px data-URI placeholder
  consent: true; basis: "club-confirmed 2026-09-30";
};
export const photos: Photo[] = [
 {
  "id": "01-01",
  "event": "club-event-01",
  "w": 1600,
  "h": 1200,
  "alt": "A presenter stands beside a projector screen while students sit at desks in a classroom.",
  "roles": [
   "dive"
  ],
  "blur": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAACwBACdASoYABIAPu1irVAppSQisBgIATAdiWcAyrQKn5jzhOVyhayrF2wPK1GAANwvp857gH1UdPzigUqLwGmgb7SNeB0Cr8SMRqcsw5SZ8oEjdDtl9aQc9jfPA7qBOVDu9TsQViCkFsJKiuoLzBpaBJsboAAA",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "01-02",
  "event": "club-event-01",
  "w": 1600,
  "h": 1200,
  "alt": "A presenter stands at a wooden lectern while students in the foreground take notes.",
  "roles": [
   "dive"
  ],
  "blur": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAACwBACdASoYABIAPu1qsFAppiSiqAqpMB2JQBgbgeennUPeexWhYeWEPq5YCZFAAPcet71bU6qR8s8RAjFNyHNiY0e5JtI2s+Xt0e0hTQHrGVqkj8xz2UI5XnELdNSJWjqYG1N5bMcdTCXgJQhNlx1uHzgbiehTQZgSAgAA",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "01-03",
  "event": "club-event-01",
  "w": 1600,
  "h": 1200,
  "alt": "Two students stand together in front of a green chalkboard and a projected slide, speaking to the room.",
  "roles": [
   "moments"
  ],
  "blur": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwBQCdASoYABIAPuFUpE2opKOiN/qoARAcCWMAt7ghuWlvVLxAMparHmySOxyHsbcEAAD9zmdyMc0IcA0u3YTCp6L3vMZmlHx0ZVhEyJrB9GtGfopdx6sBYJDqvgv2pwsnxK9qcrpXou8VZV95AAAA",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "01-04",
  "event": "club-event-01",
  "w": 1600,
  "h": 1200,
  "alt": "Two students present side by side while an audience sits at desks on the right.",
  "roles": [
   "moments"
  ],
  "blur": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAACwBACdASoYABIAPu1qrVCppaQiqAqpMB2JZQDA3BENRcUroiuzSAYabfehmEgAAP5SuMOusPbpDdYCas13K9ApMK6Nq3F72Ysy9YxZS+y2ekqWVppwSiq0jfwsxbYI7o/WSM6MN4R7vZo+8vKWvphd356eJUvCpAA=",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "01-05",
  "event": "club-event-01",
  "w": 1600,
  "h": 1200,
  "alt": "A student in a white shirt stands before a projected slide while two seated students watch.",
  "roles": [
   "moments"
  ],
  "blur": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADQBACdASoYABIAPu1mrU6ppaSiKA1RMB2JYwDM0BEgcFjhoLo8OIfwxChuzSB/4AD9zqijIpP7TLZ46FHUMbKoOokLLMOVEODIhm36n9zx9k6zewIQPS8f3/VW1NvlaR8l1CPyzqVgyn1EBsdUBgAA",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "01-06",
  "event": "club-event-01",
  "w": 1600,
  "h": 1200,
  "alt": "Two students present next to a wooden lectern in front of a projected slide.",
  "roles": [
   "gallery"
  ],
  "blur": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAQBQCdASoYABIAPu1qsFAppiUiqAqpMB2JZQDDNAeRcQJdG7nyyF1Vy8Vf4VNdFTYAAPdnDBCp0FapSRlBFebJenZ7adcb+lfPeItyXZOAqkPx8WbUPQmDswNc/J8TaBh1qA3G3R4okIlR3SAAAA==",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "01-07",
  "event": "club-event-01",
  "w": 1600,
  "h": 1200,
  "alt": "A student speaks from a lectern beside a projection screen.",
  "roles": [
   "gallery"
  ],
  "blur": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABwBACdASoYABIAPuFUpU2opCOiN/qoARAcCWUAsOwZpP2T58o4nTxCoWlKwADOIXD0yEbMKZQ7izXcYtX+cjZOCACtL6GaZ4TXVFqcK3qW63fCbeL2ujjDDLrZpuXuD53I5/Aut5pLM1RRJMc+4NtOAAA=",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "01-08",
  "event": "club-event-01",
  "w": 1200,
  "h": 1600,
  "alt": "A presenter gestures while two seated students watch from the desks in the foreground.",
  "roles": [
   "gallery"
  ],
  "blur": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAACwBQCdASoYACAAPu1sq1EppaOiqAqpMB2JYwC3uGlfzTMXxqWjlOqrzfA2ZkVeHrIUpSWSRtAA/c0GVOJiwIMHcjVMhaSOSAjXbE5Gz9UXcuGdrNBKRJI5AFJGvuHg0Pd0mGlN9FQKjFddzRMFYumy09SywRkh/0PAHuVlwJl4hrnpLS0zW2NLTexvcDvEeW2FAAAA",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "01-09",
  "event": "club-event-01",
  "w": 1600,
  "h": 1200,
  "alt": "Two presenters stand beside a lectern, one gesturing toward the audience.",
  "roles": [
   "gallery"
  ],
  "blur": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABwBQCdASoYABIAPu1irVAppSQisBgIATAdiWcAtsgKfjjSb7qz71VcWWMEb1zcw2dPRs8AAPbt0MC2TjNURaUzGrgGYyI3fzAm1tZy1k91zvSrKeHWzb5F34kAmhoJI/ZGS/dW5GDJGMRMAoSLwAAA",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "01-10",
  "event": "club-event-01",
  "w": 1600,
  "h": 1200,
  "alt": "A seated student in a checked shirt listens in the foreground while two presenters stand behind him.",
  "roles": [
   "moments"
  ],
  "blur": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADwBACdASoYABIAPu1krVAppSQisBgIATAdiWMAuzLrvCAhFO8qhIo8KRvBC5LTVUAA9yasQIqkzTghLEVfG1UjDD6ygZTXZ6F5tutwnT8GsWnqs9wH91MeJjCF9R6yyqAUSMeM+8BPJ5wBeTisT+J3R3TQbmnaaQjPZuNwAAA=",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "01-11",
  "event": "club-event-01",
  "w": 1600,
  "h": 1200,
  "alt": "Two students stand at a lectern beside a projection screen.",
  "roles": [
   "gallery"
  ],
  "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQBACdASoYABIAPuFeqk2opSQiMAwBEBwJZwDH5CBbAE/mVDbK9xEWdfoAAPqRfdETubDsQXbl0Uk3PqGfFknoZON0MAXt9dQDMiwqNFHL6mAirX2uPy7zz+eRNAdZwgAAAA==",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "01-12",
  "event": "club-event-01",
  "w": 1600,
  "h": 1200,
  "alt": "A presenter stands by a lectern while students with laptops sit at desks to the right.",
  "roles": [
   "dive"
  ],
  "blur": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACwBACdASoYABIAPu1srFCppiQiqAqpMB2JZQDKtAeHXWxa21mDzwqaFjm8ZcUAAPoKa17vgp0FZG99UAj8N8sZh2L8je2VGaPp5bmmhdgAin9B6vNqlG1ZBJJw6uTV8WT5hA+Z67w2TDbBUkr5OD8AZ/oypiAMOAAAAA==",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "01-13",
  "event": "club-event-01",
  "w": 1600,
  "h": 1200,
  "alt": "A student speaks next to a lectern with a projected slide behind him.",
  "roles": [
   "gallery"
  ],
  "blur": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAwBACdASoYABIAPu1mqE2ppaOiMAgBMB2JZwDJEB60Dl6vXU7DmvbM3KAA/h+W+x3F1J06Ddet+knVUQAplQwTm/cj5i1sO+Ep8OJ8r9kpfRORd95PscyfAxQcKGGxhp0PJt+lgAAAAA==",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "01-14",
  "event": "club-event-01",
  "w": 1600,
  "h": 1200,
  "alt": "Presenters stand at a lectern while students with laptops watch from the desks.",
  "roles": [
   "dive"
  ],
  "blur": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAwBQCdASoYABIAPu1mrE+ppSQiMBgIATAdiWcAxNgO/KdF98U06oLLl+tW0f86vMkDAAD1BWzwTOiVr7UQoi0EGqddxy5SJAkX57JBg4hCNaHlEMTt0JJaKsb++vDqjBOp21HxzXX+2l/MpD3hqHDV3pYJg6BAAAA=",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "01-15",
  "event": "club-event-01",
  "w": 1600,
  "h": 1200,
  "alt": "A student presents beside a projected slide titled 'Problem in The Mobility Sector'.",
  "roles": [
   "moments"
  ],
  "blur": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACQBACdASoYABIAPuFUpk2opKOiN/qoARAcCWUAgYYHdhfBOhiQKK8pJxrDAAAA3PgSJ56sMMyTXdFJDJ513mI4dxwuugeE8IAIREBax4MocyZ/nfLr+EHwCS/oD8eq0E77O/zXYnuXo+Y+ORQAAA==",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "02-16",
  "event": "club-event-02",
  "w": 1600,
  "h": 1035,
  "alt": "Students at tables with laptops in a classroom while others stand beside a projector screen.",
  "roles": [
   "dive"
  ],
  "blur": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABwBACdASoYABAAPu1iqk4ppaQiMAgBMB2JaACdL1ABpCIXZjcAosRxLwOiAAD+05WkzBZk32aJbxhsx13dq4VxDagBcWkaMYLJSjKEh2pwp/4/E0RBwPEZNg4cGOWFUxrCg4foZE6DcU03mVjFVbsIPMWukqilgRmtV9hr4Mw5PoJRnMAAAA==",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "02-17",
  "event": "club-event-02",
  "w": 1600,
  "h": 830,
  "alt": "A projected slide reading 'Pitch'er Perfect' with presenters standing beside the lectern.",
  "roles": [
   "dive"
  ],
  "blur": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAQBACdASoYAAwAPu1orU6ppiSiMAgBMB2JQBOmUAE+Nbg3gzfBJ10zIAD+887IAvYPULrxJHNiJ9SiEGhCuq13amW7pT++I0ZSTjpPe6jfmA0ybgHUBSzeQgVsAosg0yWOV2QTzToqyTkmr3RMfNOSFBgAAA==",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "02-18",
  "event": "club-event-02",
  "w": 1600,
  "h": 1200,
  "alt": "A projected 'Pitch'er Perfect' slide with presenters at the lectern and a listener in the foreground.",
  "roles": [
   "gallery"
  ],
  "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADwBACdASoYABIAPu1sq08ppqOiMBgIATAdiUAUkAIG5KlJgL5fKWn1F09M0GqFRYAA/sPyh7kOi1tLbCW/JXr3nTFj/wyJRSbo0RLmf/3rOOUrEPi/JjGXAayOm+H5uwUDDYSgz9JLQ/7fuI9u+loC1mdJfQ+KytEZ30cSUVV/2oRjHwORYmzAAAA=",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "02-19",
  "event": "club-event-02",
  "w": 1600,
  "h": 764,
  "alt": "A wide view of the 'Pitch'er Perfect' slide and three people at the lectern.",
  "roles": [
   "gallery"
  ],
  "blur": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABQBACdASoYAAsAPu1kqk2ppaQiMAgBMB2JZgCdMoAJ9NDy+ltGa85iuE2UAP71Hjp+77adZv0eWUIZhzJsgJSpw7GLRv5qdGhDJFWZnqI0GMx2q9D/0YGSTDwfAyKgQRRlKjko4ERjQ+aP0u9lRuPwYAA=",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "02-20",
  "event": "club-event-02",
  "w": 1600,
  "h": 1200,
  "alt": "A presentation slide on the screen while three students stand at the lectern.",
  "roles": [
   "moments"
  ],
  "blur": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADQBACdASoYABIAPu1qr1CppiQiqAqpMB2JYwCuHAejDVR9g0wSFVAMGyRnDMbAAAD+jPvQI6Vy4k05e701LreCjrdM9vhZk1i1KP7eVSKcMZVOoHTs1KQet7CBYFJZhJbH2A+xOt56O+oalYzi0xXzPyQ7c1PDlO1zzM/VkcWVFhu+EZ/XAAAA",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "02-21",
  "event": "club-event-02",
  "w": 1600,
  "h": 1200,
  "alt": "A student in a dark checked shirt stands at the lectern beside a projected slide.",
  "roles": [
   "moments"
  ],
  "blur": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBQCdASoYABIAPu1mpU2ppaMiMBgMATAdiWMAtPYgABTP9nzwn7vpxd5Sp8WeOwuAAP5TE9RxDr5EP7VJzvxCnTBOy/0Hdfj0eiCoUE59gL/yyjMfNo6xX/O1aO8rIhsOO3pwYZVB9h2P0JIXXEW0cxRFykAA",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "02-22",
  "event": "club-event-02",
  "w": 1600,
  "h": 1200,
  "alt": "Rows of students sit at wooden desks in a classroom, facing the front.",
  "roles": [
   "hero"
  ],
  "blur": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAACQBACdASoYABIAPu1urFEppqQiqAqpMB2JZQCw7BB/k6xU5wPLXY9QaqfDBBgA/lHeicQFIJl4SNAoknqNbCXQikbQuRSOUMU2jKZs2otwGFbC/9qlCzkaaJ3jNgXZDnS9HMGGhFeBwM0C6LiS92AhGjQruuAA",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "02-23",
  "event": "club-event-02",
  "w": 1600,
  "h": 1200,
  "alt": "Students seated in rows at wooden desks, looking toward a presenter.",
  "roles": [
   "dive"
  ],
  "blur": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACwBACdASoYABIAPu1oqk8ppiOiKA1RMB2JZQCw7AkbFwJej5U8iTu+chfN9bEAAP6M6ozMhjyV8heWdzUFr+7lVMWXaQGtznHGjlLpPO6kQMJ4fqBZHj8evFfZCnGnSfoT3YLqz2VGA09CXg/2cI8hKSe4kBtihQAAAA==",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "02-24",
  "event": "club-event-02",
  "w": 1600,
  "h": 1200,
  "alt": "A student stands at the lectern while others work at a table on the left.",
  "roles": [
   "gallery"
  ],
  "blur": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAwBQCdASoYABIAPuFcqE2opSQiMAwBEBwJQBWGW+BVDmDF/nbdldnLjBd4K0UW4SQIAAD+05Ut+A2ia/4eETIVrstsqn1E5+5QjE9QiGAZARgqMzFvLdAyTUZ+hkvJ4BlHJuMQum+fNVsaExPC+bi0C1bTxy2wFoA0VB9Qr+MaNJe2AAA=",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "02-25",
  "event": "club-event-02",
  "w": 1600,
  "h": 1200,
  "alt": "Presenters at the lectern beside a projected slide, students seated at a table on the left.",
  "roles": [
   "gallery"
  ],
  "blur": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAQBQCdASoYABIAPu1kqU4ppaOiMAgBMB2JQBOgBDntoaET2GKUzyfUc3dL0Kzkn3roAP5RPZKmdu4cIedGAraLWb2tqDU0o8SAX5sX0eRssRmtx1yTCPEJ/5vS1WtESer/539DWK+Xs954GEUOdmuw38QHVNMplQtLM/AA",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "02-26",
  "event": "club-event-02",
  "w": 1600,
  "h": 1200,
  "alt": "Presenters at the lectern beside a projected slide, with students at a table on the left.",
  "roles": [
   "gallery"
  ],
  "blur": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAACwBACdASoYABIAPulgo02pJaMiMAwBIB0JQBOgA3X56GXeG4eoeqs+VoHFkRfAAP5UBYmRZR8+ZzoDtBmFz51F+ayNGn5wQBx0+WO3jHOIOla52Vr9ip2uRVPKnxOKk/X9vxFj8k/Wx7iqyYNYnLPBXV5kjUUtK8Vp9qJuS8DywVJYAAA=",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "03-27",
  "event": "club-event-03",
  "w": 1600,
  "h": 900,
  "alt": "Students seated at desks in a classroom, writing on paper.",
  "roles": [
   "dive"
  ],
  "blur": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABQBACdASoYAA0APu1oqk6ppiQiMAgBMB2JaACdMoR8eCoWaEdui6JdA7PQAP5oBi1IQkpx5mEreryX/UFs4/rdlfFgkYmlfpL/PA4niNgMvpNmcG9huwmM8dVOkQfXuPnNlgAA",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "03-28",
  "event": "club-event-03",
  "w": 1600,
  "h": 1165,
  "alt": "Students seated in rows in a classroom, looking toward the front.",
  "roles": [
   "dive"
  ],
  "blur": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAACwBACdASoYABEAPu1iqU2ppaOiMBgMATAdiWUAv+wPPkO5z5LBsS36pqDezZvgAP6M6N2k0lEc4LPENA9o0FAP5Lq9isglVHqK659GbwK1lvk1wGJwAi6JgUEKEFUQQHWEXgAA",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "03-29",
  "event": "club-event-03",
  "w": 1200,
  "h": 1600,
  "alt": "A student stands beside two seated students working on a laptop.",
  "roles": [
   "moments"
  ],
  "blur": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAACwBQCdASoYACAAPu1qrVCppaQiqAqpMB2JQAq9A4ANPCepAt3GaeTHzsqj1ni1vbaFd0PTEYAA/rdI6/yDyajpRkIrZT7ihEq+1ZiT1kjy/oP0qgdue/K0pzsEdL9nqnVBcz1sU2MZYux4PQtSe8kaehrITvw8FJfPqBlfzKzz3oFWPTF4yp2HuHnBn5GWLu3XCjOcTp278ae39qmbkIgttqk7jh4nyepIUVGVIvUKZ8T1Y4AAAA==",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "03-30",
  "event": "club-event-03",
  "w": 1200,
  "h": 1600,
  "alt": "A student stands beside two seated students working on a laptop.",
  "roles": [
   "gallery"
  ],
  "blur": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAACwBQCdASoYACAAPu1qsFAppiSiqAqpMB2JYwC1CVyEZpF2JHI4w2LFWEA5kjn3rY1lCmgNuAAA/M8PnwQXrTlnC1Rxe7T0OebeGqxfsedCIPKuC3C0SA1XjZgBOqk1D10Bohq72g9ciSheAhNAm+wsWbbP930Qo0dUvE32SKKLwJ6DzCM1SzdXWI1hJtBQI3HH8ZTX7Q8Ya5XoP+RLIpRTNRsarckagV5J/gUy0YAAAA==",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "03-31",
  "event": "club-event-03",
  "w": 1200,
  "h": 1600,
  "alt": "Two students at a desk look at papers together.",
  "roles": [
   "moments"
  ],
  "blur": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAADQBQCdASoYACAAPulipE2pJaMiMAwBIB0JZACxHxgIbyEUjtaITDwjhms9N/68I1mtFYX8D2mAAP7qyIWJGfBxgjUUbEg5FHlFsj5FnJIjPlDo2vlX4zFz/pFoWe+IQJd+TjzC6RAN+ClLvXkWbmVQJbCT7h/We6WypfH54rlKOMGjxT4BkGZKmhxNFMVxX+LStMrAeXYApqLy7Qu/WePfyRYt964tHtxEwAAA",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "03-32",
  "event": "club-event-03",
  "w": 1200,
  "h": 1600,
  "alt": "Students at desks, two in the foreground looking at their papers.",
  "roles": [
   "gallery"
  ],
  "blur": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAACwBQCdASoYACAAPu1mq08ppaOiKA1RMB2JQBOmZl/IEd5c22myhV5ioqJIoWYM2sRcQ9Ci84AA/t7ndqcj+xHiyfMzRD3Lt4BjCOT602hYons6sDjz/0KevBWEp14PkhRVPYFEdOMa9KrPC8kZmP5Iyft25Qun7Jl8eV+3/7gqmoDhPU4YGUkgQTIzpj+/JCbRULwaNU0jRO2kUmRJCQBj103+NpQAAAA=",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "03-33",
  "event": "club-event-03",
  "w": 1600,
  "h": 1200,
  "alt": "A large classroom with students seated in rows and a countdown timer on the screen at the front.",
  "roles": [
   "dive"
  ],
  "blur": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACwBACdASoYABIAPu1srVCppiQiqAqpMB2JZwDKAA2ArI/Vj8vfMCubD4QIz3mAAOelyWLB9Ar0MAWNlkKSbLjpZXRTmKlHHYKCasApMRdDPMBXLL4DefZzmlK/i1YIAdI+E2ULZ2CSTmqcAAAAAA==",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "03-34",
  "event": "club-event-03",
  "w": 1600,
  "h": 1200,
  "alt": "Students seated in a classroom facing a projected countdown timer.",
  "roles": [
   "gallery"
  ],
  "blur": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAQBQCdASoYABIAPu1qr1CppiQiqAqpMB2JZQCo9A0jjk8aahbki/x0CyczIS/W/qQAAMqVq9Bqeg2NnBTiXp8hRV1KtokrQeMrZ8UmeTZXTrKBIzlhDY4ulbflG0Zsbp0cYfjj4TyQFIlcsIDFzcb4/SqwJYykYYdoAA==",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "03-35",
  "event": "club-event-03",
  "w": 1600,
  "h": 698,
  "alt": "A wide view of a classroom full of students facing a projected timer.",
  "roles": [
   "dive"
  ],
  "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAwBACdASoYAAoAPu1mqk2ppaQiMAgBMB2JYwCdABYy8x4uWP40Oxe0AAAA/e7qad5Rg0yyg6y4WWayIrCdv04aKOMAfooIFvn9CccxZvE0KCepvco+nqCBuABeS+XusVGBksigAAA=",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "03-36",
  "event": "club-event-03",
  "w": 1600,
  "h": 1200,
  "alt": "Three students gather around a laptop beside a projection screen showing a countdown timer.",
  "roles": [
   "moments"
  ],
  "blur": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABwBACdASoYABIAPu1oq04ppiQiMAgBMB2JQBUioUBXHq/JbxSwtFhenD0YKAD+w/mcz9zOjlp6VkiS19YbOUxIWJYGtEucLR24Y8OJJTGOckj3uYgRtrp2reTwI5DuCCcqx2sJstabJhujlLWkxcTgyfTmbOAA",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "03-37",
  "event": "club-event-03",
  "w": 1200,
  "h": 1600,
  "alt": "Two students at a desk in the foreground, with more seated in rows behind them.",
  "roles": [
   "gallery"
  ],
  "blur": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADQBQCdASoYACAAPuFep02opSOiMAwBEBwJZACsMy/ImfVguEBMZdSSMS75sO+3mo2pCSvJSowAAP7qh5wDwaipppvHsCjs947KlvM+lJUc2RBULQqkiViXZMSQaJARBpNV1DCmouP3XXScaReFo4ZMNt494WxzZbyqCCS0SH8nO4UJm6+miQZCf0i2nkpEa+XpBzaPYAA=",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "03-38",
  "event": "club-event-03",
  "w": 1200,
  "h": 1600,
  "alt": "A student sits at a desk with papers in a large classroom.",
  "roles": [
   "gallery"
  ],
  "blur": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAADwBACdASoYACAAPu1irU4ppaSiKA1RMB2JZQCsADKDWS7kVnqmnDOYLNEVULL2nIAA93QQ7eKdYWMDcENxszswonBTd3A8YtNI7uWi3FItnIdEUREJNDN3XGLCLFTHkqFh5WttgTgXpuPGItov1u7Bj0x5KhlQQI1yu5DoKlKDevJE995gggwCfsneD7I5eWkSh51VTqGuQji41k8AAA==",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "03-39",
  "event": "club-event-03",
  "w": 1600,
  "h": 1200,
  "alt": "Groups of students huddle over papers at desks in a large classroom with tall windows.",
  "roles": [
   "dive"
  ],
  "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAQBQCdASoYABIAPu1srVEppiQiqAqpMB2JZQC+SBEDOKpcyL3yqhMtO4EozpJHcH4AAP6LxKh2UusViH/ZHZ8sEPo3hjll6DmaUdYLMIdftEFUrx1eG6JIIDdPkT3CAgV62THBKMVS7Uuw4BfBqr0PGATr71LocQ0sSU2ai0gAAA==",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "03-40",
  "event": "club-event-03",
  "w": 1200,
  "h": 1600,
  "alt": "Students seated in a classroom with a projector screen in the distance.",
  "roles": [
   "gallery"
  ],
  "blur": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAwBQCdASoYACAAPu1mq08ppaOiKA1RMB2JZQC+SEToJWaTazJqZuOb+rW55utHglIcAAD+aaN7uCW6ebOs4qU0I7myn1fNOssY6n6fmzHb3LB620JQ+wLFy2oosDweeFeoD3CfCJvUuiLnL1sP9NoEHSQvgi66EWTKdy/BlkJ9mVJsj79nT6VcsJxu17YqQIi0zgAA",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 },
 {
  "id": "03-41",
  "event": "club-event-03",
  "w": 1600,
  "h": 1200,
  "alt": "A student stands at the side of a classroom while others sit facing a projected screen.",
  "roles": [
   "dive"
  ],
  "blur": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAACQBACdASoYABIAPu1or1AppaSiqAqpMB2JYwCdAAiJDcZB3JyNyL90gCpMQaYAzNnxfX1cIcBy/tL6/RgjoV5JYxN37+AvHgCv273lTLhZDq5q+bXQs3K8BylJu4Q/g4N4iVycH5IEwCvbAvGCN6pTAvoJeFmAAAA=",
  "consent": true,
  "basis": "club-confirmed 2026-09-30"
 }
];
