// Generated by scripts/build-posters.mjs. Do not edit.
export const posterBlur: Record<string, string> = {
  "vv-announcement": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAACwAwCdASoQABcAPu1iqU2ppaOiMAgBMB2JZQAAW/Cn7q0pG52W4AD+7NIicWvBizXy/6LInQABO8cLVD7/rtoKpuc2xIoeZwelEpdwSnd17Xwoc9lVZ4JcwSmh1i3SdtqKQm7MjfQArKyu+txsrfFIkmQB6Oa3T9ze5A9qDRuKIAAA",
  "vv-why": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABwAwCdASoQABcAPu1iqk2ppaQiMAgBMB2JaQDA3DKLJtNGxaAA/vCi0uUbf4Tszw7UKURQnNrCGdDJyFVROIzF2rJ4GbPPJ1vAAA=="
};
