// Generated by scripts/build-posters.mjs. Do not edit.
export const posterBlur: Record<string, string> = {
  "vv-announcement": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAACwAwCdASoQABcAPu1iqU2ppaOiMAgBMB2JZQAAW/Cn7q0pG52W4AD+7NIicWvBizXy/6LInQABO8cLVD7/rtoKpuc2xIoeZwelEpdwSnd17Xwoc9lVZ4JcwSmh1i3SdtqKQm7MjfQArKyu+txsrfFIkmQB6Oa3T9ze5A9qDRuKIAAA",
  "vv-tracks": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAADwAwCdASoQABcAPu1iqU2ppaOiMAgBMB2JYgC7ABZULML59ydHaxHAAP7v1fxCAOgRYj+NcUUxuOVAsJhw99wQh14QycTiHygwweoIJhTv7ClwT08FMuEcPfB3SiSpf3xuEYtLmsbObtf5fpHfycT4Hx3a5V7zmt724kB0c0rY62yxii+CDAnrs4aPLDtEMsNW7JVgYyFh3fYAL/IQgAAA",
  "vv-timeline": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABwBACdASoQABcAPu1iqk2ppaQiMAgBMB2JZQDE3agR+oy/9jqvQrczP2aWgAD+7eB98czV+OSsN69/wQfRl7dsujCpv65RSs0d2SSWtR4FavFdfJE6fTqT0quh2EInsRceS+f38nHBg/h//5uJ9MLWvuGr+9iXC/lddouTScN4VvLbJcdy0AASNUHfeyIZZcXCc+bsoC1xdoeAAAA=",
  "vv-why": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABwAwCdASoQABcAPu1iqk2ppaQiMAgBMB2JaQDA3DKLJtNGxaAA/vCi0uUbf4Tszw7UKURQnNrCGdDJyFVROIzF2rJ4GbPPJ1vAAA=="
};
